name: build

on:
  pull_request:
  merge_group:
  push:
    branches: [main]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

permissions: {}

jobs:
  crate-checks:
    name: Check that crates compile on their own
    runs-on: ubuntu-latest
    timeout-minutes: 90 # cold run takes a lot of time as each crate is compiled separately
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install Rust toolchain
        run: |
          rustup toolchain install nightly --profile minimal
          rustup default nightly

      - name: Rust cache
        uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2
        with:
          cache-on-failure: true

      - name: Install cargo-hack
        uses: taiki-e/install-action@5b4d68e2e660441203ab128a23676f1e4faf1532 # cargo-hack v2.86.3
        with:
          tool: cargo-hack

      - name: Rust cache
        uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2
        with:
          cache-on-failure: true

      - name: Configure sccache
        run: |
          echo "RUSTC_WRAPPER=sccache" >> "$GITHUB_ENV"
          echo "SCCACHE_GHA_ENABLED=true" >> "$GITHUB_ENV"

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@fc920bf0ec8de6ee65d409111f7ec508035751ba # v0.0.11
        with:
          version: "v0.10.0" # sccache version

      - name: Install FoundationDB client library
        uses: $/.github/actions/setup-foundationdb-client

      - name: Check crates compile
        run: cargo hack check
        env:
          DATABASE_URL: sqlite://./operator.db
